Linux-Hardened: Restore align_vdso_addr
Clang16 and 17 throw a C99 error for the missing `align_vdso_addr`
function referenced in arch/x86/entry/vdso/vma.c. Daniel removed
it in 06aba60cf x86_64: move vdso to mmap region from stack region.

Restore the function delcalration and header without reverting the
original mapping mechanism using `vdso_addr` in vma.c.

Fixes:
```
error: call to undeclared function 'align_vdso_addr'; ISO C99 and
later do not support implicit function declarations
[-Wimplicit-function-declaration]
```